name: CoderStatus
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  cloud_firestore: ^2.1.0
  fluttertoast: ^8.0.7
  image_picker: ^0.8.0+3
  image_cropper: ^1.4.0
  path: ^1.8.0
  firebase_storage: ^8.1.3
  http: ^0.13.3
  html: ^0.14.0+3
  rive: ^0.7.27
  flutter_phoenix: ^1.0.0
  rect_getter: ^1.0.0
  glassmorphism_ui: ^0.2.0
  dotted_border: ^2.0.0+1
  argon_buttons_flutter: ^1.1.0
  url_launcher: ^6.0.9
  font_awesome_flutter: ^9.1.0
  google_sign_in: ^5.0.3
  provider: ^5.0.0
  internet_connection_checker: ^0.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/skeleton-place-holder.riv
    - assets/shine.riv
    - assets/cup.riv
    - assets/boy-scene.riv
    - assets/crown.riv
    - assets/no-peers.riv
    - assets/search-user.riv
    - assets/cup-crying.riv
  fonts:
    - family: Young
      fonts:
        - asset: fonts/young.ttf
    - family: Headline
      fonts:
        - asset: fonts/Headline.TTF
